export const ProductDetail = [
  {
    id: 123456543,
    name: "New Apple iPhone 10",
    rating: "34565",
    review: "1000",
    emi: "2401",
    delivery: "Wednesday, Aug 18",
    price: "50999",
    status: "In stock",
    soldby: "Darshita Electronics",
    image: "New-Apple-iPhone-10.jpg",
    about: [
      "6.1-inch (15.5 cm diagonal) Liquid Retina HD LCD display, ",
      "Water and dust resistant (2 meters for up to 30 minutes, IP68)",
      "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps",
      "Face ID for secure authentication",
    ],
  },
  {
    id: 54342265,
    name: "New Apple iPhone 11 - Purple",
    rating: "34565",
    review: "1000",
    emi: "2401",
    delivery: "Wednesday, Aug 18",
    price: "50999",
    status: "In stock",
    soldby: "Darshita Electronics",
    image: "New-Apple-iPhone-11.jpg",
    about: [
      "Desription for iphone 11 -bla bla",
      "6.1-inch (15.5 cm diagonal) Liquid Retina HD LCD display",
      "Water and dust resistant (2 meters for up to 30 minutes, IP68)",
      "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps",
      "Face ID for secure authentication",
    ],
  },
  {
    id: 123453456543,
    name: "Apple iPhone 12 - Blue",
    rating: "34565",
    review: "1000",
    emi: "2401",
    delivery: "Wednesday, Aug 18",
    price: "76543",
    status: "In stock",
    soldby: "Darshita Electronics",
    image: "Apple-iPhone12-Blue.jpg",
    about: [
      "Desription for iphone 12 -bla bla",
      "6.1-inch (15.5 cm diagonal) Liquid Retina HD LCD display",
      "Water and dust resistant (2 meters for up to 30 minutes, IP68)",
      "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps",
      "Face ID for secure authentication",
    ],
  },
  {
    id: 12344545456543,
    name: "Apple iPhone 13 Mini - Green",
    rating: "34565",
    review: "1000",
    emi: "2401",
    delivery: "Wednesday, Aug 18",
    price: "637357",
    status: "In stock",
    soldby: "Darshita Electronics",
    image: "Apple-iPhone13Mini-Green.jpg",
    about: [
      "Desription for iphone 13 -bla bla",
      "6.1-inch (15.5 cm diagonal) Liquid Retina HD LCD display",
      "Water and dust resistant (2 meters for up to 30 minutes, IP68)",
      "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps",
      "Face ID for secure authentication",
    ],
  },
  {
    id: 123465656543,
    name: "Apple iPhone 12 - White",
    rating: "34565",
    review: "1000",
    emi: "2401",
    delivery: "Wednesday, Aug 18",
    price: "76543",
    status: "In stock",
    soldby: "Darshita Electronics",
    image: "Apple-iPhone12-White.jpg",
    about: [
      "Desription for iphone 12 pro pmax -bla bla",
      "6.1-inch (15.5 cm diagonal) Liquid Retina HD LCD display",
      "Water and dust resistant (2 meters for up to 30 minutes, IP68)",
      "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps",
      "Face ID for secure authentication",
    ],
  },
  {
    id: 2356346363,
    name: "Apple iPhone 13 Pro - Graphite",
    rating: "637357",
    review: "1000",
    emi: "2401",
    delivery: "Wednesday, Aug 18",
    price: "50999",
    status: "In stock",
    soldby: "Darshita Electronics",
    image: "Apple-iPhone-13Pro-Graphite.jpg",
    about: [
      "Desription for iphone 13 -bla mini bla",
      "6.1-inch (15.5 cm diagonal) Liquid Retina HD LCD display",
      "Water and dust resistant (2 meters for up to 30 minutes, IP68)",
      "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps",
      "Face ID for secure authentication",
    ],
  },
  {
    id: 23563465473,
    name: "Apple iPhone 14 Pro Max",
    rating: "637357",
    review: "1000",
    emi: "7197",
    delivery: "Wednesday, Aug 18",
    price: "149900",
    status: "In stock",
    soldby: "Darshita Electronics",
    image: "Apple-iPhone-14-Pro-Max.jpg",
    about: [
      "17.00 cm (6.7-inch) Super Retina XDR display featuring Always-On and ProMotion",
      "Dynamic Island, a magical new way to interact with iPhone",
      "48MP Main camera for up to 4x greater resolution",
      "Cinematic mode now in 4K Dolby Vision up to 30 fps",
      "Action mode for smooth, steady, handheld videos",
    ],
  },
  {
    id: 235634473,
    name: "Apple iPhone 14 - Midnight",
    rating: "637357",
    review: "1000",
    emi: "3440",
    delivery: "Wednesday, Aug 18",
    price: "71999",
    status: "In stock",
    soldby: "Darshita Electronics",
    image: "Apple-iPhone-14-Midnight.jpg",
    about: [
      "17.00 cm (6.7-inch) Super Retina XDR display featuring Always-On and ProMotion",
      "Dynamic Island, a magical new way to interact with iPhone",
      "48MP Main camera for up to 4x greater resolution",
      "Cinematic mode now in 4K Dolby Vision up to 30 fps",
      "Action mode for smooth, steady, handheld videos",
    ],
  },
];

export const WatchDetail = [
  {
    id: 789654,
    name: "Fire-Boltt Phoenix Smart",
    rating: "34565",
    review: "1000",
    emi: "87",
    delivery: "Wednesday, Aug 18",
    price: "1799",
    status: "In stock",
    image: "Fire-Boltt-Phoenix-Smart.jpg",
    about: [
      "Fire-Boltt is India' No 1 Wearable Watch Brand",
      "Q122 by IDC Worldwide quarterly wearable",
      "device tracker Q122.【Bluetooth Calling Watch】- Fire-Boltt Phoenix enables you to",
      "make and receive calls directly from your watch via the built-in speaker and microphone.",
    ],
  },
  {
    id: 471852,
    name: "beatXP Vega 1.43 AMOLED 466",
    rating: "34565",
    review: "1000",
    emi: "97",
    delivery: "Wednesday, Aug 18",
    price: "1,999",
    status: "In stock",
    image: "beatXP-Vega.jpg",
    about: [
      "1.43” Round AMOLED Display: The beatXP Vega Smart watch comes with Full Touch",
      "AMOLED Display. Its sleek bezels allow you to experience the smart watch with renewed",
      "performance. With customizable cloud-based",
      "watch faces, you can change your smart watch’s face every day.",
      "Face ID for secure authentication",
    ],
  },
  {
    id: 321456,
    name: "Noise Pulse Go Buzz Smart",
    rating: "34565",
    review: "1000",
    emi: "82",
    delivery: "Wednesday, Aug 18",
    price: "1699",
    status: "In stock",
    image: "Noise-PulseGo-Buzz-Smart.jpg",
    about: [
      "Sharp and bright display: The 1.69’’ TFT display with 240*280px and 500 nits brightness ensures",
      "visual treat every time you look at the watch",
      "BT calling: Stay in touch with your friends - right from your wrist. Battery Capacity : 300mAh",
      "Utility features: Use the utility features at your disposal and become more productive - get",
      "hand wash reminders, idle alert and drink water reminder, weather forecast, set alarms and more",
    ],
  },
  {
    id: 741963,
    name: "boAt Wave Call Smart Watch",
    rating: "34565",
    review: "1000",
    emi: "2401",
    delivery: "Wednesday, Aug 8",
    price: "1799",
    status: "In stock",
    image: "boAt-Wave-Call-Smart-Watch.jpg",
    about: [
      "Sharp and bright display: The 1.69’’ TFT display with 240*280px and 500 nits brightness ensures",
      "visual treat every time you look at the watch",
      "BT calling: Stay in touch with your friends - right from your wrist. Battery Capacity : 300mAh",
      "Utility features: Use the utility features at your disposal and become more productive - get",
      "hand wash reminders, idle alert and drink water reminder, weather forecast, set alarms and more",
    ],
  },
  {
    id: 852654,
    name: "beatXP Marv Super 1.99",
    rating: "34565",
    review: "1000",
    emi: "102",
    delivery: "Wednesday, Aug 14",
    price: "2099",
    status: "In stock",
    image: "beatXP-Marv-Super.jpg",
    about: [
      "Sharp and bright display: The 1.69’’ TFT display with 240*280px and 500 nits brightness ensures",
      "visual treat every time you look at the watch",
      "BT calling: Stay in touch with your friends - right from your wrist. Battery Capacity : 300mAh",
      "Utility features: Use the utility features at your disposal and become more productive - get",
      "hand wash reminders, idle alert and drink water reminder, weather forecast, set alarms and more",
    ],
  },
  {
    id: 753951,
    name: "Noise Pulse 2 Max Advanced",
    rating: "637357",
    review: "1000",
    emi: "2401",
    delivery: "Wednesday, Aug 1",
    price: "1999",
    status: "In stock",
    image: "Noise-Pulse2-Max-Advanced.jpg",
    about: [
      "Sharp and bright display: The 1.69’’ TFT display with 240*280px and 500 nits brightness ensures",
      "visual treat every time you look at the watch",
      "BT calling: Stay in touch with your friends - right from your wrist. Battery Capacity : 300mAh",
      "Utility features: Use the utility features at your disposal and become more productive - get",
      "hand wash reminders, idle alert and drink water reminder, weather forecast, set alarms and more",
    ],
  },
  {
    id: 789654,
    name: "Vibez by Lifelong Ornate Smartwatch",
    rating: "637357",
    review: "1000",
    emi: "121",
    delivery: "Wednesday, May 14",
    price: "2498",
    status: "In stock",
    image: "Vibezby-Lifelong-Ornate-Smartwatch.jpg",
    about: [
      "Vibez Ornate is a Premium metallic watch for women",
      "Vibez Ornate’s large HD screen transitions into a sleek metal body",
      "Heart Rate Monitoring: The length of the heart rate page on the hand ring can measure your current heart rate",
      "This page can display the data of your previous heart rate info",
      "More detailed information can be viewed on the app synchronously",
    ],
  },
  {
    id: 456321,
    name: "Vibez by Lifelong Smartwatch",
    rating: "637357",
    review: "1000",
    emi: "3440",
    delivery: "Wednesday, Aug 7",
    price: "1998",
    status: "In stock",
    image: "Vibezby-Lifelong-Smartwatch.jpg",
    about: [
      "Bluetooth Call Notifications: With just a tap of a button",
      "you can synchronize your mobile phone via Bluetooth to receive call notifications",
      "even when you are on the go. This feature makes communication more efficient and helps you stay",
      "connected to your phone even when you’re away from it",
      "Vibez smartwatches are compatible with both Android and IOS devices",
    ],
  },
];

export const LaptopDetail = [
  {
    id: 123456,
    name: "Dell XPS 15 Laptop",
    rating: "4.8",
    review: "350",
    emi: "3479",
    delivery: "Monday, May 23",
    price: "84999",
    status: "In stock",
    image: "dell-xps-15.jpg",
    about: [
      "Experience stunning visuals with the Dell XPS 15 laptop",
      "Featuring a 15.6-inch 4K OLED display, you'll enjoy vibrant colors and deep blacks",
      "Powerful performance with an Intel Core i7 processor and 16GB of RAM",
      "512GB SSD provides ample storage for all your files and programs",
      "Backlit keyboard for comfortable typing in any lighting conditions",
    ],
  },
  {
    id: 234567,
    name: "Lenovo ThinkPad X1 Carbon",
    rating: "4.7",
    review: "270",
    emi: "2599",
    delivery: "Friday, May 27",
    price: "79999",
    status: "In stock",
    image: "lenovo-thinkpad-x1-carbon.jpg",
    about: [
      "The Lenovo ThinkPad X1 Carbon is the ultimate business laptop",
      "Featuring a 14-inch Full HD display and up to 18.3 hours of battery life",
      "Intel Core i7 processor and 16GB of RAM for powerful performance",
      "512GB SSD provides ample storage for all your files and programs",
      "Built-in fingerprint reader for secure and easy login",
    ],
  },

  {
    id: 345678,
    name: "Asus ZenBook Pro Duo UX582",
    rating: "4.5",
    review: "120",
    emi: "7549",
    delivery: "Tuesday, May 24",
    price: "189999",
    status: "In stock",
    image: "asus-zenbook-pro-duo-ux582.jpg",
    about: [
      "Experience the future of computing with the Asus ZenBook Pro Duo UX582",
      "Featuring a 15.6-inch 4K OLED display and a secondary 14-inch 4K touchscreen display",
      "Powerful performance with an Intel Core i9 processor and 32GB of RAM",
      "1TB SSD provides ample storage for all your files and programs",
      "Innovative ScreenPad Plus for enhanced productivity",
    ],
  },

  {
    id: 456789,
    name: "HP Spectre x360",
    rating: "4.6",
    review: "450",
    emi: "4799",
    delivery: "Thursday, May 26",
    price: "119999",
    status: "In stock",
    image: "hp-spectre-x360.jpg",
    about: [
      "The HP Spectre x360 is the ultimate 2-in-1 laptop",
      "Featuring a 13.3-inch Full HD touchscreen display that rotates 360 degrees",
      "Intel Core i7 processor and 16GB of RAM for powerful performance",
      "512GB SSD provides ample storage for all your files and programs",
      "Built-in fingerprint reader for secure and easy login",
    ],
  },

  {
    id: 567890,
    name: "Apple MacBook Pro",
    rating: "4.9",
    review: "650",
    emi: "8999",
    delivery: "Wednesday, May 25",
    price: "179999",
    status: "In stock",
    image: "apple-macbook-pro.jpg",
    about: [
      "Experience the power and beauty of the Apple MacBook Pro",
      "Featuring a 16-inch Retina display with True Tone technology",
      "Intel Core i9 processor and 16GB of RAM for powerful performance",
      "1TB SSD provides ample storage for all your files and programs",
      "Touch Bar and Touch ID for enhanced productivity and security",
    ],
  },
  {
    id: 789012,
    name: "MSI GE76 Raider",
    rating: "4.3",
    review: "190",
    emi: "5899",
    delivery: "Monday, May 23",
    price: "147999",
    status: "In stock",
    image: "msi-ge76-raider.jpg",
    about: [
      "Dominate your gaming competition with the MSI GE76 Raider",
      "Featuring a 17.3-inch Full HD display with 240Hz refresh rate and 3ms response time",
      "Intel Core i7 processor and 16GB of RAM for powerful gaming performance",
      "1TB SSD provides ample storage for all your games and files",
      "NVIDIA GeForce RTX 3080 graphics card for stunning visuals",
    ],
  },

  {
    id: 890123,
    name: "Razer Blade 15",
    rating: "4.8",
    review: "420",
    emi: "6599",
    delivery: "Wednesday, May 25",
    price: "164999",
    status: "In stock",
    image: "razer-blade-15.jpg",
    about: [
      "Experience the ultimate gaming laptop with the Razer Blade 15",
      "Featuring a 15.6-inch Full HD display with 144Hz refresh rate and 3ms response time",
      "Intel Core i7 processor and 16GB of RAM for powerful gaming performance",
      "1TB SSD provides ample storage for all your games and files",
      "NVIDIA GeForce RTX 3080 graphics card for stunning visuals",
    ],
  },

  {
    id: 901234,
    name: "Dell G5 15",
    rating: "4.2",
    review: "150",
    emi: "2799",
    delivery: "Thursday, May 26",
    price: "69999",
    status: "In stock",
    image: "dell-g5-15.jpg",
    about: [
      "Get the perfect balance of performance and affordability with the Dell G5 15 gaming laptop",
      "Featuring a 15.6-inch Full HD display with 120Hz refresh rate",
      "Intel Core i7 processor and 16GB of RAM for smooth gaming performance",
      "512GB SSD provides ample storage for all your games and files",
      "NVIDIA GeForce RTX 3060 graphics card for stunning visuals",
    ],
  },

  {
    id: 1234567,
    name: "LG Gram 17",
    rating: "4.5",
    review: "90",
    emi: "4799",
    delivery: "Friday, May 27",
    price: "119999",
    status: "In stock",
    image: "lg-gram-17.jpg",
    about: [
      "Experience lightweight portability with the LG Gram 17 laptop",
      "Featuring a 17-inch Full HD display and weighing only 1.35 kg",
      "Intel Core i7 processor and 16GB of RAM for powerful performance",
      "1TB SSD provides ample storage for all your files and programs",
      "Up to 19.5 hours of battery life for all-day use",
    ],
  },
];

export const headphonesDetail = [
  {
    id: 123456789,
    name: "Sony WH-1000XM4",
    rating: "4.7",
    review: "2800",
    emi: "2099",
    delivery: "Monday, May 23",
    price: "29990",
    status: "In stock",
    image: "sony-wh-1000xm4.jpg",
    about: [
      "Experience industry-leading noise cancellation with the Sony WH-1000XM4 headphones",
      "Featuring 40mm drivers for powerful, balanced sound",
      "Up to 30 hours of battery life for all-day listening",
      "Advanced noise-cancelling technology blocks out background noise",
      "Touch controls allow for easy music and call management",
    ],
  },

  {
    id: 741852963,
    name: "Bose QuietComfort 35 II",
    rating: "4.6",
    review: "2400",
    emi: "1899",
    delivery: "Wednesday, May 25",
    price: "26900",
    status: "In stock",
    image: "bose-quietcomfort-35-ii.jpg",
    about: [
      "Experience the ultimate in noise-cancelling headphones with the Bose QuietComfort 35 II",
      "Featuring Alexa and Google Assistant voice control",
      "Up to 20 hours of battery life for all-day listening",
      "Advanced noise-cancelling technology blocks out background noise",
      "Comfortable ear cushions and headband for extended wear",
    ],
  },

  {
    id: 753963852741,
    name: "Sennheiser Momentum 3",
    rating: "4.5",
    review: "1800",
    emi: "2599",
    delivery: "Thursday, May 26",
    price: "38990",
    status: "In stock",
    image: "sennheiser-momentum-3.jpg",
    about: [
      "Experience superior sound quality with the Sennheiser Momentum 3 headphones",
      "Featuring active noise-cancelling technology for immersive listening",
      "Up to 17 hours of battery life for all-day listening",
      "Voice assistant support with Alexa, Google Assistant, and Siri",
      "Smart controls allow for easy music and call management",
    ],
  },

  {
    id: 25896321,
    name: "Jabra Elite 85h",
    rating: "4.4",
    review: "1500",
    emi: "2099",
    delivery: "Friday, May 27",
    price: "24999",
    status: "In stock",
    image: "jabra-elite-85h.jpg",
    about: [
      "Experience the best-in-class noise-cancelling with the Jabra Elite 85h headphones",
      "Featuring advanced SmartSound technology for personalized sound",
      "Up to 36 hours of battery life for all-day listening",
      "Voice assistant support with Alexa, Google Assistant, and Siri",
      "Smart controls allow for easy music and call management",
    ],
  },
  {
    id: 987456987,
    name: "Apple AirPods Pro",
    rating: "4.8",
    review: "3200",
    emi: "1799",
    delivery: "Monday, May 30",
    price: "24900",
    status: "In stock",
    image: "apple-airpods-pro.jpg",
    about: [
      "Experience the magic of AirPods with the Apple AirPods Pro",
      "Featuring active noise cancellation for immersive listening",
      "Up to 24 hours of battery life with the charging case",
      "Sweat and water-resistant design for sports and workouts",
      "Easy setup and automatic on/off with all Apple devices",
    ],
  },

  {
    id: 741852962,
    name: "Bowers & Wilkins PX7",
    rating: "4.7",
    review: "2600",
    emi: "3499",
    delivery: "Wednesday, Jun 1",
    price: "43999",
    status: "In stock",
    image: "bowers-wilkins-px7.jpg",
    about: [
      "Experience the best of wireless headphones with the Bowers & Wilkins PX7",
      "Featuring adaptive noise cancellation for customizable listening",
      "Up to 30 hours of battery life for all-day listening",
      "Voice assistant support with Google Assistant and Siri",
      "Premium design and materials for ultimate comfort and durability",
    ],
  },

  {
    id: 326598754,
    name: "Beats Studio3 Wireless",
    rating: "4.5",
    review: "1900",
    emi: "2199",
    delivery: "Thursday, Jun 2",
    price: "27900",
    status: "In stock",
    image: "beats-studio3-wireless.jpg",
    about: [
      "Experience the iconic Beats sound with the Beats Studio3 Wireless headphones",
      "Featuring active noise cancellation for immersive listening",
      "Up to 22 hours of battery life for all-day listening",
      "Apple W1 chip for seamless connection with Apple devices",
      "Comfortable over-ear design with adjustable fit",
    ],
  },

  {
    id: 96587452145,
    name: "JBL Live 650BTNC",
    rating: "4.4",
    review: "1500",
    emi: "1299",
    delivery: "Friday, Jun 3",
    price: "17999",
    status: "In stock",
    image: "jbl-live-650btnc.jpg",
    about: [
      "Experience powerful sound and noise cancellation with the JBL Live 650BTNC headphones",
      "Featuring a massive 40mm driver for high-quality sound",
      "Up to 30 hours of battery life for all-day listening",
      "Voice assistant support with Google Assistant and Alexa",
      "Sleek and stylish design with foldable ear cups for easy storage",
    ],
  },
];
